- name: Demo on variables
  hosts: all
  vars:
    URL: maniknata.url.com
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: " {{ URL }} "


- name: Demo on task level variables
  hosts: all
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: task level -  {{ URL }}
      vars:
        URL: task.maniknata.url.com